# Copyright (c) TigardHighGDC
# SPDX-License-Identifier: Apache-2.0

name: Clang Format Check
on:
  push:
    branches:
      - '**' # All branches
  pull_request:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            result = os.system('python3 Tests/clang_format_check.py')
            if result != 0:
              exit(1)
            else:
              exit(0)
